# Numpy Library:

In [3]:
import numpy as np

we can work on array with the help of numpy library in python.

In [4]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
type(a)

numpy.ndarray

In [6]:
# creating a 2d array

a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# creating a 3d array
# if dimensions is more then layers of brackets is also more

a3 = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]


In [8]:
type(a3)

numpy.ndarray

# Methods of Numpy:

In [9]:
print(a2.shape)
# it tells the number of rows and columns.

(2, 5)


In [10]:
print(a2.ndim)
# it tells the dimensions of array.

2


In [11]:
print(a2.dtype)
# it tells the datatype of elements which is store in array.

int64


In [12]:
np.arange(10)
# it directly create the array and then store the values.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
np.random.randint(1,11, size =(2,3))

array([[1, 9, 2],
       [2, 5, 5]], dtype=int32)

In [16]:
x = np.array([[7,2,3],
             [2,5,2],
             [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)


[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [19]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [18]:
np.dot(x,y)  #matrix multiplication


array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [20]:
x.prod()   #product of all elements of the array


np.int64(12600)

In [21]:
x.mean()  #mean of all elements

np.float64(3.3333333333333335)

In [24]:
print(x)

[[7 2 3]
 [2 5 2]
 [3 5 1]]


In [22]:
x.mean(axis = 0)   #column wise mean

array([4., 4., 2.])

In [23]:
y.mean(axis = 1)   #row wise mean

array([4.        , 4.        , 3.33333333])

In [25]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [26]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25))    #1st quartile
print(np.percentile(a,50))    #median
print(np.percentile(a,75))    #3rd quartile

3.0
5.0
7.0


In [36]:
b =np.random.randint(11,100,(4,4))
print(b)

[[75 55 80 71]
 [99 37 84 34]
 [75 51 78 25]
 [54 50 91 84]]


In [37]:
print('2x8')
print(b.reshape(2,8))
print('8x2')
print(b.reshape(8,2))

2x8
[[75 55 80 71 99 37 84 34]
 [75 51 78 25 54 50 91 84]]
8x2
[[75 55]
 [80 71]
 [99 37]
 [84 34]
 [75 51]
 [78 25]
 [54 50]
 [91 84]]


In [34]:
print(x[0])  #1st row
print(x[0,1])   #1st row and 2nd column's first element
print(x[-1])

print(x[:3])
print(x[3:])

[7 2 3]
2
[3 5 1]
[[7 2 3]
 [2 5 2]
 [3 5 1]]
[]
